### ISSUE TITLE
accessory unavailable when debug turned off

### ISSUE THREAD

**Issue by jmissig** [aphex3k/homebridge-bloomsky#12]
I couldn't get the Bloomsky accessory to appear in Home. I killed and restarted Homebridge a number of times. Eventually I turned on debug. Not sure if that was the trigger, but I was able to manually add the Bloomsky accessory.

However, once I turned off debug and restarted the homebridge, the accessory was no longer available.

1. "debug": false, Unable to add accessory.
2. "debug": true, Added accessory fine.
3. "debug": false again, Accessory unavailable.
4. "debug": true again, Accessory back.

I have a SKY2.

**Comment by swamplynx** [comment]
Same issue with my SKY2 as well.

**Comment by DifferentComputers** [comment]
Same.

**Comment by aphex3k** [comment]
I'm currently rewriting the module with support for latest homebridge. Can you please test version `https://www.npmjs.com/package/homebridge-bloomsky/v/1.2.0-alpha.0`?
