### ISSUE TITLE
snapshots don't seem to be generated at the correct location

### ISSUE THREAD

**Issue by jmissig** [aphex3k/homebridge-bloomsky#13]
My node prefix is set as `prefix=/home/julian/node_modules`. Snapshots do not work for me. Live video works fine (!). I have a SKY2.

Debug output says
`[4/6/2019, 3:14:17 PM] [Bloomsky] Delivering snapshot at path: /home/julian/node_modules/node_modules/homebridge-bloomsky/lib/4286befb-a627-417a-9bd2-65b957718cb4.jpg
[4/6/2019, 3:14:17 PM] [Bloomsky] ... using Sharp`

That path doesn't look quite right. Not really sure where temporary data is supposed to live, but the beginning part should be `/home/julian/node_modules/lib/node_modules/homebridge-bloomsky`

**Comment by jmissig** [comment]
Uneducated guess is that temp file generation should be using `homebridge.user.storagePath()` somehow.

**Comment by swamplynx** [comment]
Were you ever able to fix this? I am having the same issue.

**Comment by jmissig** [comment]
No I gave up on trying to fix it myself. I've found trying to develop for homebridge plugins quite frustrating.

**Comment by swamplynx** [comment]
I ended up hacking around it by creating a symbolic link from where it was actually creating the snapshot, to where it was looking for it. In my case...

sudo ln -s /home/pi/5dc98f96-1040-43c4-a685-63b355c71429.jpg /usr/node_modules/homebridge-bloomsky/lib/5dc98f96-1040-43c4-a685-63b355c71429.jpg

**Comment by aphex3k** [comment]
@swamplynx If this works for you I definitely will look at the section handling the preview file. I just need to find some time...

**Comment by swamplynx** [comment]
Yep. Snapshorts are working perfectly for me now. I needed to change some permissions as well. Some additional information that may help troubleshoot.

My 'npm config get prefix' is '/usr,' and my modules install into '/usr/lib/node_modules'

The plugin is creating snapshots in /home/pi, which is the user in which I have homebridge running under.

I created a link to that file, from both /usr/node_modules/homebridge-bloomsky/lib/ (where the debug log indicates it is looking), and the actual directory where the plugin, /usr/lib/node_modules/homebridge-bloomsky/lib/, and updated permissions to those folders. I haven't bothered removing one link other the other to determine where the plugin is actually pulling the snapshot from, but it is working perfectly now.

**Comment by schpeen** [comment]
Can you guys help me out. I got the Bloomksy NPM running on Homebridge on my Pi and the data is showing correctly in Home app but the video image wont show I keep getting an error. Any ideas ? Appreciate any help.

**Comment by DifferentComputers** [comment]
Running HOOBS on a Mac and have the video feed working (as long as debug:true) but snapshots don't seem to be generating at all. I think Home app is grabbing a snapshot from the vid stream.

The above discussion seems to suggest that the plugin may be creating a snapshot, but it only references pi installs. Where would I try to find it when it's not on a pi?

**Comment by aphex3k** [comment]
Can you please test version `https://www.npmjs.com/package/homebridge-bloomsky/v/1.2.0-alpha.0`? It is a rewrite of the module and does not use local snapshot files anymore.

**Comment by jmissig** [comment]
Just tried — the new version launches and I get a few of my accessories, but just a test pattern for the video feed.

I see there’s another issue stating Sky2 is not actually currently supported. Funny because that’s what I was using before!

I’ll investigate further this weekend maybe and might file an issue with more details.
