### ISSUE TITLE
Bloomsky doesn't show up in home app

### ISSUE THREAD

**Issue by zirdum** [aphex3k/homebridge-bloomsky#14]
I added the plugin with the proper API, but I don't have anything that shows up in the home app. The status for the homebridge service shows an occasional [Bloomsky] New accessory pushed... (about every 2.5 minutes)

Any idea what I can do for it to show up?

**Comment by swamplynx** [comment]
Same issue here.. Did you ever resolve?

**Comment by aphex3k** [comment]
I have not experienced the issue yet and also have not run into it myself. Sorry guys.

**Comment by swamplynx** [comment]
Leaving debug to "true" was the only way I was able to get the device to show. After adding, debug must be left as true, or the device drops.

**Comment by schpeen** [comment]
anyone figure this out?? I am having same problem. But when I set debug to "true" it seems to cause my homebridge to keeping going on and off. Once I go back to false the homebridge is fine. Any tips??

Also is the Bloomsky API suppose to have an = sign at the end of it, or should I remove that?

**Comment by misterwiggles** [comment]
Same issue here. Just installed this plugin and in the Hoobs log it appears to be working and communicating with the Bloomsky API. Just nothing showing up in HOME app. Would appreciate some help with this.

**Comment by misterwiggles** [comment]
Update: I now see that if I set debug to TRUE that I had to go into Add Accessory manually and my Bloomsky shows up. However it is asking me for a 8 digit Homekit setup code for this. Where do I get that?

**Comment by DifferentComputers** [comment]
Can confirm that only debug:true allowed this to work for me too. If I hadn't read this thread and tried that, I would have had to uninstall this plugin from HOOBS.

**Comment by mishakim** [comment]
I'm having the same problem, but even setting debug to TRUE didn't fix it. Tried adding accessory and manually entering the bridge's HomeKit code (that's what you do for homebridge cameras), but still nothing showed up. Restarted homebridge and now it crashes as soon as it tries to pull updated data from Bloomsky. Set debug back to false and it stopped crashing, but still no accessory.

**Comment by aphex3k** [comment]
Can you please test version `https://www.npmjs.com/package/homebridge-bloomsky/v/1.2.0-alpha.0`?
